#!/bin/dash

# c-template - writes a template for a c function

if [ ! $1 ]; then
    echo "usage: c-template comments"
    exit 1
fi

# comments=$1

cat << _EOF_
/* $@ */
#include <stdio.h>

int main(void) {
    return 0;
}
_EOF_
