#!/usr/bin/dash

# according to the labels on the controller:

# 1 sends Left, 3 sends Right
# 2 sends XF86_AudioMute
# 4 sends space
# 5 and 6 send XF86_AudioLowerVolume and XF86_AudioRaiseVolume
# 7 and 8 send XF86_AudioPrev and XF86_AudioNext
# "select" sends XF86AudioMedia, which makes dwm start mpd
# "start" sends XF86AudioPlay, 
# with light on, clicking analog sticks send XF86_MonBrightnessDown or XF86_MonBrightnessUp

# joymouse -v -o /tmp/joymouse -B key=space -B key=XF86_AudioMute -B key=Right -B key=4 -B key=XF86_AudioLowerVolume -B key=XF86_AudioRaiseVolume -B key=XF86_AudioPrev -B key=XF86_AudioNext -B key=XF86_AudioMedia -B key=XF86_AudioPlay
# joymouse -v -o /tmp/joymouse -B key=space -B key=XF86_AudioMute -B key=Right -B key=4 -B key=XF86_MonBrightnessDown -B key=XF86_MonBrightnessUp -B key=XF86_AudioPrev -B key=XF86_AudioNext -B key=XF86_AudioMedia -B key=XF86_AudioPlay
# joymouse -v -o /tmp/joymouse -t joypad -t joypad -t joypad -B key=space -B key=XF86_AudioMute -B key=Right -B key=4 -B key=XF86_MonBrightnessDown -B key=XF86_MonBrightnessUp -B key=XF86_AudioPrev -B key=XF86_AudioNext -B key=XF86_AudioMedia -B key=XF86_AudioPlay
joymouse -v -i /dev/input/by-id/usb-GreenAsia_Inc._USB_Joystick-joystick -o /tmp/joymouse -B key=Left -B key=XF86_AudioMute -B key=Right -B key=space -B key=XF86_MonBrightnessDown -B key=XF86_MonBrightnessUp -B key=XF86_AudioLowerVolume -B key=XF86_AudioRaiseVolume -B key=XF86_AudioMedia -B key=XF86_AudioPlay -B key=XF86_AudioPrev -B key=XF86_AudioNext -M x -M y -M x -M y -M x -M y
