#!/bin/dash

filename=$(tail -n 1 ~/.fehbg | awk '{ print $3 }' | tr -d "'")

# use zenity if not running in a terminal 
if [ -t 0 ] ; then
    echo -n "really remove: $filename ? (y/n) "
    read confirmation
else 
    zenity --question --text="really remove:  $filename ? (y/n) " && confirmation="y"
fi

if [ "$confirmation" = "y" ]; then
    rm "$filename" && 
        if [ -t 0 ]; then
            echo "behold! the deed is done."
        else 
            zenity --info --text="behold! the deed is done."
        fi
else
    echo "$0: not deleting $filename"
fi
