#!/bin/dash
# a customized version of dmenu_run, 9.9
# aug 22 2014

# cache only the things you will actually run, instead of everything in $PATH
# remember to sort this file periodically!
cache="$HOME/.cache/dmenu_launcher"

program=$(dmenu < "$cache") || exit
exec "$program"
