#!/usr/bin/dash
# dependencies: dmenu, mpc

playlist_item=$(mpc playlist | dmenu -i -l 4)

if [ "$?" = 1 ]; then
    zenity --warning --text="did you hit ESC?"
    exit 1
fi

mpc searchplay "$playlist_item"
