#!/usr/bin/dash
# dependencies: dmenu, zenity

filename=$(mpc listall --format="%file%" | dmenu -i -l 4)
if [ "$?" = 1 ]; then
#     zenity --warning --text="did you hit ESC?"
    exit 1
fi

mpc add "$filename"
mpc playlist --format="%file%" | wc -l | xargs mpc play --quiet
