#!/bin/dash
# dependencies: feh

# put this in crontab
# current wallpaper stored in ~/.fehbg

if [ $# -eq 1 ]; then
    # set wallpaper with commandline arg
    pic=$1;
else
    # pic one at random
    pic=$(find $HOME/pics/wallpapers/ -type f | shuf --head-count=1)
    # use this to count frequency 
    echo "[$(date +'%F %R')] $pic" >> "$HOME/pics/wallpaper.log"
fi;

dimensions=$(feh -L "%w %h" $pic)
# ratio=$(feh -L "%w %h" $pic | awk '{ print $1/$2-1.77 }')

# this should actually try to handle the ratio instead of exact size
if [ "$dimensions" = "1366 768" ]; then
    # if ratio is the same as the resolution, might as well scale it
    exec feh --bg-fill "$pic"
else
    # if ratio is wrong, just center and cut some stuff off
    exec feh --bg-center "$pic"
fi
# --bg-center --bg-fill --bg-max --bg-scale --bg-tile
