#!/usr/bin/dash

[ "$(hostname)" = "multivac" ] || exit 1

# flips the xorg output, rotates the touchscreen, disables the touchpad

if [ "$1" = "-u" ] ; then
    xrandr --output eDP-1 --rotate inverted
    xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
    xinput --disable "DLL064D:00 06CB:2985"
else
    xrandr --output eDP-1 --rotate normal
    xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
    xinput --enable "DLL064D:00 06CB:2985"
fi
